name = "cloudpulse-staging"
main = "worker/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist" }

[[d1_databases]]
binding = "DB"
database_name = "cloudpulse-d1-staging"
database_id = "REPLACE_WITH_STAGING_D1_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_WITH_STAGING_KV_ID"

[triggers]
crons = ["*/15 * * * *"]
